services:
  - type: web
    name: booktalk-api
    env: node
    buildCommand: cd server && npm install
    startCommand: cd server && npm start
    envVars:
      - key: JWT_SECRET
        generateValue: true
      - key: PORT
        value: 5001
    healthCheckPath: /health
